spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/dinerop
    username: dinerop_user
    password: dinerop_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: mi-super-secret-key-para-desarrollo-con-minimo-32-caracteres-de-longitud
  expiration: 86400000

logging:
  level:
    org.hibernate.SQL: debug

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:5174